### ISSUE TITLE
Focus

### ISSUE THREAD

**Issue by thomtomdup** [kamran8545/artistic_multilingual_keyboards#4] opened 2022-10-13 09:07 UTC
Hello.
I tried youre good package in my project. It have an issue when i want to click on button when the fied have the focus, the keyboad disappaer automaticaly ( because the field is unfocus, _isKeyboardOpen is automaticaly set to false ).
This was tested with a Mac app in flutter.
Thank you.

**Comment by kamran8545** [comment] 2022-10-13 13:03
@thomtomdup thank you for reporting this issue.. kinldy tell me which button you are clicking on? is it back button of device?

**Comment by thomtomdup** [comment] 2022-10-13 13:25
Hello.
It is all buttons.
When you click on a keyboard button, automaticaly focus go outside of the field, the focusnode detect an unfocus and automaticaly the listener set false to _isKeyboardOpen.

**Comment by kamran8545** [comment] 2022-10-14 04:33
Can you share your code snippet?? Are you using pandown event of Gesture detector to remove focus in your screen??

**Comment by thomtomdup** [comment] 2022-10-14 07:44
Hello.
This is not my code, i tested it with your example code.

**Comment by kamran8545** [comment] 2022-10-14 07:55
That's weird I am using the same example and unable to reproduce this error..

**Comment by thomtomdup** [comment] 2022-10-14 08:36
Hello.
Have you test it with a mac os desktop app generated ?

**Comment by thomtomdup** [comment] 2022-10-17 21:40
Hello.
Is it possible for you to test with desktop Mac app ? 😊

**Comment by kamran8545** [comment] 2022-10-18 07:23
@thomtomdup this package is for only Android & iOS devices, we have not added other OS support yet. And i have tested it on iOS devices it's working fine. I am closing this issue now. If you have any other question or query kindly do report it.

Thanks for your time.

**Closed as completed by kamran8545** 2022-10-18 07:23 UTC

**Comment by thomtomdup** [comment] 2022-10-18 07:26
Hello.

Ok so please change the platform list in the pub.dev website to set only Android and IOS.
Thank you for your comments and support.
